# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-30 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180331_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.Category', verbose_name='\u5206\u7c7b'),
        ),
    ]
